### ISSUE TITLE
Unable to Add New Chart URL

### ISSUE THREAD

**Issue by incubator4** [Azure/k8s-bake#83]
I am using the azure/k8s-bake repository as part of my GitHub Actions workflow to render Kubernetes yaml resource manifests using Helm. However, I am encountering an issue where I am unable to add new chart URLs to the repository.

I have tried using the arguments parameter to pass in the --repo flag with the URL of the new chart repository, as well as using the helm repo add command to add the new chart repository before running the helm template command. However, neither of these methods seem to have any effect.

due to run the `helm dependency update` command , it appears to fail when attempting to retrieve charts from remote repositories, resulting in errors that prevent my workflow from completing successfully. Specifically, I am receiving error messages indicating that the remote chart repository is not accessible or that it cannot be found.

It might be like this.
```
/usr/bin/unzip -o -q /home/runner/work/_temp/b66e215b-7c6e-4950-b1d7-094a40964c34
Running helm dependency update command..
/opt/hostedtoolcache/helm/3.11.3/x64/linux-amd64/helm dependency update <my-chart>/<my-app>
Error: could not find naturalselectionlabs/web-app: stat <my-chart>/<my-app>: no such file or directory
Error: Failed to run bake action. Error: Error: The process '/opt/hostedtoolcache/helm/3.11.3/x64/linux-amd64/helm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/azure/k8s-bake/v2.4/lib/index.js:31[16](https://github.com/NaturalSelectionLabs/Daedalus/actions/runs/4782724271/jobs/8502343921#step:7:17):25)
    at ExecState.CheckComplete (/home/runner/work/_actions/azure/k8s-bake/v2.4/lib/index.js:3099:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/k8s-bake/v2.4/lib/index.js:2993:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
/home/runner/work/_actions/azure/k8s-bake/v2.4/lib/index.js:7427
                throw Error(util.format('Failed to run bake action. Error: %s', err));
                      ^
```

Any sugguestion for feature? I'm glad to create PR.

**Comment by Abdul-Arfat-Mohammed** [comment]
Is this issue still being considered? I'm encountering the same problem with k8s-bake v3 when trying to use the Apache Airflow chart from its official repository.
